### ISSUE TITLE
DATA: Additional Details Model & Migration

### ISSUE THREAD

**Issue by ShriHumrudha** [Mums-Who-Code/SCMS.Services#181]
Model - https://github.com/Mums-Who-Code/SCMS.Services/blob/main/SCMS.Services.Api/Designs/AdditionalDetails.jpg

**Comment by rcruzfreelance** [comment]
do we have any specific on what properties to use for this model?

**Comment by ShriHumrudha** [comment]
> do we have any specific on what properties to use for this model?

Updated the model link in the description.

**Comment by rcruzfreelance** [comment]
Hello Shri thanks for the model. I would still need to create the broker in order to do the migrations. I will reference this issue to the broker issue for this.

**Comment by ShriHumrudha** [comment]
> Hello Shri thanks for the model. I would still need to create the broker in order to do the migrations. I will reference this issue to the broker issue for this.

Yes, you are right. The existing broker issues are for the CRUD operation. So this issue focuses on the broker to define the data set and the references for migration.
