### ISSUE TITLE
MINOR FIX: Change EmailId to Email

### ISSUE THREAD

**Issue by ShriHumrudha** [Mums-Who-Code/SCMS.Services#241]

**Comment by RishiKumarRay** [comment]
Can you elaborate this issue

**Comment by ShriHumrudha** [comment]
> Can you elaborate this issue

The Guardian and Guardian Request Model has an attribute called EmailId. This attribute should be renamed to Email. The task involves - Model & Migration, Guardian Foundation, GuardianRequest Processing.
